package com.rabkov.musictracks.command;

public enum CommandType {
    GO_TO_START_PAGE_COMMAND,
    GO_TO_USERS_PAGE_COMMAND,
    GO_TO_LOGIN_PAGE_COMMAND,
    GO_TO_SIGN_UP_PAGE_COMMAND,
    GO_TO_EDIT_PRODUCT_PAGE_COMMAND,
    GO_TO_ACTIVATION_PAGE_COMMAND,
    GO_TO_MANAGER_PAGE,
    GO_TO_PRODUCT_PAGE,
    DEFAULT,
    START_PAGE_COMMAND,
    LOGIN_COMMAND,
    SIGN_UP_COMMAND,
    ACTIVATE_COMMAND,
    LOG_OUT_COMMAND,
    EDIT_NEW_PRODUCT_COMMAND;
}
